[package]
name = "tsq1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["std"]
std = []

[dependencies]
midly = { version = "0.5", default-features = false, features = ["alloc"] }
